source :rubygems

gem 'nanoc'
gem 'fssm'
gem 'mime-types'
gem 'kramdown'
gem 'nokogiri'
gem 'adsf'
gem 'haml', '~> 3.2.0.rc.1'
gem 'builder'
gem 'activesupport'
gem 'uglifier'
gem 'systemu'
gem 'rake', '~> 0.9.2.2'
gem 'kramdown-gist'
